FROM node:22-slim AS base

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Variables públicas de Next.js (necesarias en tiempo de build)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SQT_SUPABASE_URL
ARG NEXT_PUBLIC_SQT_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_SQT_SUPABASE_URL=$NEXT_PUBLIC_SQT_SUPABASE_URL
ENV NEXT_PUBLIC_SQT_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SQT_SUPABASE_ANON_KEY

RUN npm run build

EXPOSE 3000

ENV HOSTNAME="0.0.0.0"

CMD ["npm", "start"]
